version: "3.4"
services:
  dockerexpress:
    build:
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./myapp:/usr/src/app:delegated
      - ./myapp/node_modules:/usr/src/app/node_modules:delegated
    ports:
      - 3000:3000
  my_mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_mysql_db
    ports:
      - "3300:3300"
    volumes:
      - my_volume:/var/lib/mysql
volumes:
  my_volume:
